---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mandeep96/Microservices-with-Spring-Cloud
          searchPaths: ConfigData
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8001